## Pandas library
Pandas is very powerful data manuplation language which is used for data analysis and data cleaning.  
It Provides Primary two data Structure Series and DataFrame. Series is 1d array like object and datafrsme is 2d dimentional,size-mutble  
and potentially hetrogenus tabular data structure which provides which labled axes(rows and coloumns)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in d:\data analysis\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\data analysis\venv\lib\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\data analysis\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\data analysis\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\data analysis\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\data analysis\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
num=[1,2,3,4,5]

series_pd=pd.Series(num)
print(series_pd)
print(type(series_pd))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:

#If we want to define own Index
dictionary_pd={"A":1,"B":2,"C":3,"D":4}
new_series=pd.Series(dictionary_pd)
print(new_series)

A    1
B    2
C    3
D    4
dtype: int64

In [5]:
data=[1,2,3,4,5]
index=["A","B","C","D","E"]
new_series=pd.Series(data,index=index)
print(new_series)

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [6]:
data={
    "Name":["Hasan","Ibrahim","Maryam"],
    "Age":[23,60,50],
    "City":["Ajara","Kolhapur","Anaf"],
    "Gender":["M","M","F"]
}

df=pd.DataFrame(data)
print(df)

      Name  Age      City Gender
0    Hasan   23     Ajara      M
1  Ibrahim   60  Kolhapur      M
2   Maryam   50      Anaf      F

In [7]:
new_data=[
    {"Name":"Hasan","Age":23,"City":"Ajara","Gender":"M"},
    {"Name":"Hasan","Age":23,"City":"Ajara","Gender":"M"},
    {"Name":"Hasan","Age":23,"City":"Ajara","Gender":"M"},
    {"Name":"Hasan","Age":23,"City":"Ajara","Gender":"M"}
]
data_data=pd.DataFrame(new_data)
print(data_data)

    Name  Age   City Gender
0  Hasan   23  Ajara      M
1  Hasan   23  Ajara      M
2  Hasan   23  Ajara      M
3  Hasan   23  Ajara      M

In [8]:
pf=pd.read_csv("data.csv")

In [9]:
pf.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [10]:
pf.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [11]:
df

      Name  Age      City Gender
0    Hasan   23     Ajara      M
1  Ibrahim   60  Kolhapur      M
2   Maryam   50      Anaf      F

In [12]:
df['Name']

0      Hasan
1    Ibrahim
2     Maryam
Name: Name, dtype: object

In [13]:
df.loc[0][0] ##Row index

C:\Users\Hasan PC\AppData\Local\Temp\ipykernel_19164\3012496438.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0] ##Row index

'Hasan'

In [14]:
df.iloc[0][2] #coloumn index

C:\Users\Hasan PC\AppData\Local\Temp\ipykernel_19164\2336582399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2] #coloumn index

'Ajara'

In [15]:
df

      Name  Age      City Gender
0    Hasan   23     Ajara      M
1  Ibrahim   60  Kolhapur      M
2   Maryam   50      Anaf      F

In [16]:
#Specified element

df.at[1,'Name']

'Ibrahim'

In [17]:
df.iat[2,2]

'Anaf'

# Data Manuplation using Pandas

In [ ]:
df['Salary']=[60000,50000,40000]

In [19]:
df

      Name  Age      City Gender  Salary
0    Hasan   23     Ajara      M   60000
1  Ibrahim   60  Kolhapur      M   50000
2   Maryam   50      Anaf      F   40000

In [23]:
# df.drop('Salary') it will give error because the default is rows axis we have to make maually 1
df.drop('Salary',axis=1,inplace=True) #this also cannot delete it permanently so you have to use inplace

In [24]:
df

      Name  Age      City Gender
0    Hasan   23     Ajara      M
1  Ibrahim   60  Kolhapur      M
2   Maryam   50      Anaf      F

In [27]:
df['Age']=df['Age']+1
df

      Name  Age      City Gender
0    Hasan   26     Ajara      M
1  Ibrahim   63  Kolhapur      M
2   Maryam   53      Anaf      F

In [31]:
df.drop(0,inplace=True)

In [32]:
df

      Name  Age      City Gender
1  Ibrahim   63  Kolhapur      M
2   Maryam   53      Anaf      F

In [36]:
print("The DataType",pf.dtypes)

The DataType Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [38]:
print("Descibeing the statistical Information",pf.describe())

Descibeing the statistical Information            Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [39]:
pf.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000